package net.eiradir.content

import net.eiradir.server.item.EquipmentSlot
import net.eiradir.server.plugin.Initializer
import net.eiradir.server.registry.RegistryBuilders

class Items(define: RegistryBuilders) : Initializer {

    val appleTree = define.item("apple_tree_01_full") { tag("fruit_tree") }
    val appleTree2 = define.item("apple_tree_02_full") { tag("fruit_tree") }
    val appleTree3 = define.item("apple_tree_03_full") { tag("fruit_tree") }
    val beehiveActive = define.item("beehive_active")
    val rubyAmulet = define.item("ruby_amulet")

    init {
        define.item("admin_construction")
        define.item("admin_creation")
        define.item("admin_deletion")
        define.item("admin_manipulation")
        define.item("admin_terrain")
        define.item("alchemist_lens")
        define.item("alchemist_monocle")
        define.item("alchemist_set")
        define.item("colendulum_potion_base")
        define.item("distillation_vessel")
        define.item("neiralium_potion_base")
        define.item("triandulum_potion_base")
        define.item("emerald_amulet")
        define.item("sapphire_amulet")
        define.item("beehive")
        define.item("blood")
        define.item("blood_e")
        define.item("blood_n")
        define.item("blood_ne")
        define.item("blood_nw")
        define.item("blood_s")
        define.item("blood_se")
        define.item("blood_sw")
        define.item("blood_w")
        define.item("black_book")
        define.item("book_overlay")
        define.item("red_book")
        define.item("wooden_bridge_ew")
        define.item("wooden_bridge_ns")
        define.item("campfire")
        define.item("campfire_active")
        define.item("campfire_with_kettle")
        define.item("big_cart_e")
        define.item("big_cart_n")
        define.item("cart")
        define.item("cloth")
        define.item("cloth_pattern_01")
        define.item("cloth_pattern_02")
        define.item("cloth_pattern_03")
        define.item("cloth_pattern_04")
        define.item("cloth_pattern_05")
        define.item("cabbage_crop_stage_01")
        define.item("cabbage_crop_stage_02")
        define.item("cabbage_crop_stage_03")
        define.item("carrot_crop_stage_01")
        define.item("carrot_crop_stage_02")
        define.item("carrot_crop_stage_03")
        define.item("grape_crop_stage_01")
        define.item("grape_crop_stage_02")
        define.item("grape_crop_stage_03")
        define.item("grape_crop_stage_04")
        define.item("lorma_crop_stage_01")
        define.item("lorma_crop_stage_02")
        define.item("lorma_crop_stage_03")
        define.item("lorma_crop_stage_04")
        define.item("onion_crop_stage_01")
        define.item("onion_crop_stage_02")
        define.item("onion_crop_stage_03")
        define.item("rye_crop_stage_01")
        define.item("rye_crop_stage_02")
        define.item("rye_crop_stage_03")
        define.item("tomato_crop_stage_01")
        define.item("tomato_crop_stage_02")
        define.item("tomato_crop_stage_03")
        define.item("watermelon_crop_stage_01")
        define.item("watermelon_crop_stage_02")
        define.item("watermelon_crop_stage_03")
        define.item("watermelon_crop_stage_04")
        define.item("wheat_crop_stage_01")
        define.item("wheat_crop_stage_02")
        define.item("wheat_crop_stage_03")
        define.item("black_crystal")
        define.item("blue_crystal")
        define.item("green_crystal")
        define.item("pink_crystal")
        define.item("purple_crystal")
        define.item("red_crystal")
        define.item("yellow_crystal")
        define.item("clay_mug")
        define.item("clay_mug_overlay")
        define.item("copper_goblet")
        define.item("goblet_overlay")
        define.item("golden_goblet")
        define.item("grail_of_lelei")
        define.item("grail_of_lelei_overlay")
        define.item("iron_goblet")
        define.item("silver_goblet")
        define.item("wooden_cup")
        define.item("fire_01")
        define.item("fire_02")
        define.item("frozen_puddle")
        define.item("ice_tile")
        define.item("lava")
        define.item("water_puddle")
        define.item("arrow")
        define.item("bolt")
        define.item("pebble")

        define.item("archers_fingerless_gloves") { equipmentSlot = EquipmentSlot.Gloves }
        define.item("archers_steel_cap") { equipmentSlot = EquipmentSlot.Head }
        define.item("arme_helmet") { equipmentSlot = EquipmentSlot.Head }
        define.item("banded_chain_haubergeon") { equipmentSlot = EquipmentSlot.Torso }
        define.item("banded_chain_hauberk") { equipmentSlot = EquipmentSlot.Torso }
        define.item("barbut_helm") { equipmentSlot = EquipmentSlot.Head }
        define.item("basinet") { equipmentSlot = EquipmentSlot.Head }
        define.item("chained_jack") { equipmentSlot = EquipmentSlot.Torso }
        define.item("chain_coif") { equipmentSlot = EquipmentSlot.Head }
        define.item("chain_gloves") { equipmentSlot = EquipmentSlot.Gloves }
        define.item("chain_leggings") { equipmentSlot = EquipmentSlot.Legs }
        define.item("clamshell_helmet") { equipmentSlot = EquipmentSlot.Head }
        define.item("closed_helmet") { equipmentSlot = EquipmentSlot.Head }
        define.item("cloth_gloves") { equipmentSlot = EquipmentSlot.Gloves }
        define.item("cursed_plate") { equipmentSlot = EquipmentSlot.Torso }
        define.item("dark_elf_armor") { equipmentSlot = EquipmentSlot.Torso }
        define.item("death_plate") { equipmentSlot = EquipmentSlot.Torso }
        define.item("dome_riveted_chain_haubergeon") { equipmentSlot = EquipmentSlot.Torso }
        define.item("dome_riveted_chain_hauberk") { equipmentSlot = EquipmentSlot.Torso }
        define.item("drow_leather") { equipmentSlot = EquipmentSlot.Torso }
        define.item("dwarven_hammerfist_heavy_plate") { equipmentSlot = EquipmentSlot.Torso }
        define.item("dwarven_hammerfist_plate") { equipmentSlot = EquipmentSlot.Torso }
        define.item("dwarven_plated_chain") { equipmentSlot = EquipmentSlot.Torso }
        define.item("elven_chain_shirt") { equipmentSlot = EquipmentSlot.Torso }
        define.item("flesh_of_koshmar") { equipmentSlot = EquipmentSlot.Torso }
        define.item("full_chain_coif") { equipmentSlot = EquipmentSlot.Head }
        define.item("full_guarded_chain_coif") { equipmentSlot = EquipmentSlot.Head }
        define.item("full_leather_armor") { equipmentSlot = EquipmentSlot.Torso }
        define.item("full_steel_gauntlets") { equipmentSlot = EquipmentSlot.Gloves }
        define.item("gambeson") { equipmentSlot = EquipmentSlot.Torso }
        define.item("guarded_chain_coif") { equipmentSlot = EquipmentSlot.Head }
        define.item("guarded_steel_cap") { equipmentSlot = EquipmentSlot.Head }
        define.item("heavy_closed_helmet") { equipmentSlot = EquipmentSlot.Head }
        define.item("heavy_knight_plate") { equipmentSlot = EquipmentSlot.Torso }
        define.item("hunting_jacket") { equipmentSlot = EquipmentSlot.Torso }
        define.item("improved_leather_cap") { equipmentSlot = EquipmentSlot.Head }
        define.item("improved_mercenary_plate") { equipmentSlot = EquipmentSlot.Torso }
        define.item("improved_studded_leather_cap") { equipmentSlot = EquipmentSlot.Head }
        define.item("invari_assassin_armor") { equipmentSlot = EquipmentSlot.Torso }
        define.item("ironclad_horned_helmet") { equipmentSlot = EquipmentSlot.Head }
        define.item("jawbone_sallet") { equipmentSlot = EquipmentSlot.Head }
        define.item("kassarean_mercenary_plate") { equipmentSlot = EquipmentSlot.Torso }
        define.item("kassarean_officer_plate") { equipmentSlot = EquipmentSlot.Torso }
        define.item("kassarean_skullhound_bascinet") { equipmentSlot = EquipmentSlot.Head }
        define.item("kassar_skullhound_bascinet") { equipmentSlot = EquipmentSlot.Head }
        define.item("klapviser_bascinet") { equipmentSlot = EquipmentSlot.Head }
        define.item("leather_boots") { equipmentSlot = EquipmentSlot.Feet }
        define.item("leather_cap") { equipmentSlot = EquipmentSlot.Head }
        define.item("leather_fingerless_gloves") { equipmentSlot = EquipmentSlot.Gloves }
        define.item("leather_gloves") { equipmentSlot = EquipmentSlot.Gloves }
        define.item("leather_helmet") { equipmentSlot = EquipmentSlot.Head }
        define.item("leather_leggings") { equipmentSlot = EquipmentSlot.Legs }
        define.item("leather_shoes") { equipmentSlot = EquipmentSlot.Feet }
        define.item("light_crusader_helmet") { equipmentSlot = EquipmentSlot.Head }
        define.item("light_knight_plate") { equipmentSlot = EquipmentSlot.Torso }
        define.item("light_leather_armor") { equipmentSlot = EquipmentSlot.Torso }
        define.item("light_plate_cuirass") { equipmentSlot = EquipmentSlot.Torso }
        define.item("magical_malphite_armor") { equipmentSlot = EquipmentSlot.Torso }
        define.item("magical_sapphire_leather_armor") { equipmentSlot = EquipmentSlot.Torso }
        define.item("magical_teranium_armor") { equipmentSlot = EquipmentSlot.Torso }
        define.item("orc_marauder_armor") { equipmentSlot = EquipmentSlot.Torso }
        define.item("padded_gambeson") { equipmentSlot = EquipmentSlot.Torso }
        define.item("pigface_basinet") { equipmentSlot = EquipmentSlot.Head }
        define.item("plated_chain_gloves") { equipmentSlot = EquipmentSlot.Gloves }
        define.item("plated_jack") { equipmentSlot = EquipmentSlot.Torso }
        define.item("plated_leather_boots") { equipmentSlot = EquipmentSlot.Feet }
        define.item("plated_leather_mercenary_armor") { equipmentSlot = EquipmentSlot.Torso }
        define.item("ranger_jacket") { equipmentSlot = EquipmentSlot.Torso }
        define.item("riveted_chain_haubergeon") { equipmentSlot = EquipmentSlot.Torso }
        define.item("riveted_chain_hauberk") { equipmentSlot = EquipmentSlot.Torso }
        define.item("sallet") { equipmentSlot = EquipmentSlot.Head }
        define.item("short_chain_leggings") { equipmentSlot = EquipmentSlot.Legs }
        define.item("short_leather_leggings") { equipmentSlot = EquipmentSlot.Legs }
        define.item("short_steel_leggings_greaves") { equipmentSlot = EquipmentSlot.Legs }
        define.item("steel_gauntlets") { equipmentSlot = EquipmentSlot.Gloves }
        define.item("steel_leggings_greaves") { equipmentSlot = EquipmentSlot.Legs }
        define.item("steel_plate") { equipmentSlot = EquipmentSlot.Torso }
        define.item("steel_sabatons") { equipmentSlot = EquipmentSlot.Feet }
        define.item("studded_leather_armor") { equipmentSlot = EquipmentSlot.Torso }
        define.item("studded_leather_cap") { equipmentSlot = EquipmentSlot.Head }
        define.item("studded_leather_gloves") { equipmentSlot = EquipmentSlot.Gloves }
        define.item("studded_leather_leggings") { equipmentSlot = EquipmentSlot.Legs }
        define.item("studded_mercenary_armor") { equipmentSlot = EquipmentSlot.Torso }
        define.item("sugarloaf_helmet") { equipmentSlot = EquipmentSlot.Head }
        define.item("teutonic_helmet") { equipmentSlot = EquipmentSlot.Head }
        define.item("maruvian_corazina") { equipmentSlot = EquipmentSlot.Torso }
        define.item("maruvian_crusader_helmet") { equipmentSlot = EquipmentSlot.Head }
        define.item("maruvian_knight_plate") { equipmentSlot = EquipmentSlot.Torso }
        define.item("trigadi_bladeweaver_armor") { equipmentSlot = EquipmentSlot.Torso }
        define.item("very_evil_helmet") { equipmentSlot = EquipmentSlot.Head }
        define.item("visored_sallet") { equipmentSlot = EquipmentSlot.Head }
        define.item("archmage_robe") { equipmentSlot = EquipmentSlot.Torso }
        define.item("archmage_robe_overlay") { equipmentSlot = EquipmentSlot.Torso }
        define.item("ball_dress") { equipmentSlot = EquipmentSlot.Torso }
        define.item("ball_dress_overlay") { equipmentSlot = EquipmentSlot.Torso }
        define.item("blouse_01") { equipmentSlot = EquipmentSlot.Torso }
        define.item("blouse_02") { equipmentSlot = EquipmentSlot.Torso }
        define.item("blouse_03") { equipmentSlot = EquipmentSlot.Torso }
        define.item("blouse_04") { equipmentSlot = EquipmentSlot.Torso }
        define.item("blouse_05") { equipmentSlot = EquipmentSlot.Torso }
        define.item("blouse_06") { equipmentSlot = EquipmentSlot.Torso }
        define.item("cloak_of_methos") { equipmentSlot = EquipmentSlot.Back }
        define.item("cloth_hat") { equipmentSlot = EquipmentSlot.Head }
        define.item("cultist_robe") { equipmentSlot = EquipmentSlot.Torso }
        define.item("cultist_robe_overlay") { equipmentSlot = EquipmentSlot.Torso }
        define.item("dress") { equipmentSlot = EquipmentSlot.Legs }
        define.item("dress_overlay") { equipmentSlot = EquipmentSlot.Legs }
        define.item("fancy_dress") { equipmentSlot = EquipmentSlot.Legs }
        define.item("fancy_dress_overlay") { equipmentSlot = EquipmentSlot.Legs }
        define.item("festive_hat") { equipmentSlot = EquipmentSlot.Head }
        define.item("fitted_tunic") { equipmentSlot = EquipmentSlot.Torso }
        define.item("fitted_tunic_overlay") { equipmentSlot = EquipmentSlot.Torso }
        define.item("fur_jack") { equipmentSlot = EquipmentSlot.Torso }
        define.item("fur_leggings") { equipmentSlot = EquipmentSlot.Legs }
        define.item("gray_long_coat") { equipmentSlot = EquipmentSlot.Torso }
        define.item("hood") { equipmentSlot = EquipmentSlot.Head }
        define.item("hood_open") { equipmentSlot = EquipmentSlot.Head }
        define.item("jack") { equipmentSlot = EquipmentSlot.Torso }
        define.item("long_cloak") { equipmentSlot = EquipmentSlot.Back }
        define.item("mage_robe") { equipmentSlot = EquipmentSlot.Torso }
        define.item("mage_robe_overlay") { equipmentSlot = EquipmentSlot.Torso }
        define.item("master_wizard_hat") { equipmentSlot = EquipmentSlot.Head }
        define.item("merchant_cloak") { equipmentSlot = EquipmentSlot.Back }
        define.item("noble_shirt") { equipmentSlot = EquipmentSlot.Torso }
        define.item("peasant_hat") { equipmentSlot = EquipmentSlot.Head }
        define.item("priest_robe") { equipmentSlot = EquipmentSlot.Torso }
        define.item("priest_robe_overlay") { equipmentSlot = EquipmentSlot.Torso }
        define.item("ranger_cloak") { equipmentSlot = EquipmentSlot.Back }
        define.item("red_cloak") { equipmentSlot = EquipmentSlot.Back }
        define.item("scholar_robe") { equipmentSlot = EquipmentSlot.Torso }
        define.item("shirt") { equipmentSlot = EquipmentSlot.Torso }
        define.item("shirt_02") { equipmentSlot = EquipmentSlot.Torso }
        define.item("shirt_03") { equipmentSlot = EquipmentSlot.Torso }
        define.item("shirt_04") { equipmentSlot = EquipmentSlot.Torso }
        define.item("shirt_05") { equipmentSlot = EquipmentSlot.Torso }
        define.item("shirt_06") { equipmentSlot = EquipmentSlot.Torso }
        define.item("sorcerer_cloaked_coat") { equipmentSlot = EquipmentSlot.Torso }
        define.item("stylish_hat") { equipmentSlot = EquipmentSlot.Head }
        define.item("trousers") { equipmentSlot = EquipmentSlot.Legs }
        define.item("tunic") { equipmentSlot = EquipmentSlot.Torso }
        define.item("warm_fur_hat") { equipmentSlot = EquipmentSlot.Head }
        define.item("white_feathered_hat") { equipmentSlot = EquipmentSlot.Head }
        define.item("wizard_hat") { equipmentSlot = EquipmentSlot.Head }
        define.item("wizard_hood") { equipmentSlot = EquipmentSlot.Head }
        define.item("wreath_of_priroda") { equipmentSlot = EquipmentSlot.Head }

        define.item("buckler")
        define.item("demonic_shield")
        define.item("heater_shield")
        define.item("heraldic_shield")
        define.item("kite_shield")
        define.item("lowland_shield")
        define.item("oxen_shield")
        define.item("red_knight_shield")
        define.item("round_shield")
        define.item("scutum_shield")
        define.item("sun_shield")
        define.item("tower_shield")
        define.item("wall_shield")
        define.item("wooden_shield")
        define.item("albion_longsword")
        define.item("arming_sword")
        define.item("armored_bow")
        define.item("axe")
        define.item("backsword")
        define.item("ball_mace")
        define.item("bastard_sword")
        define.item("berdische")
        define.item("broadsword")
        define.item("claymore")
        define.item("club")
        define.item("composite_bow")
        define.item("crossbow")
        define.item("dagger")
        define.item("dirk")
        define.item("double_axe")
        define.item("dwarven_axe")
        define.item("elven_blade")
        define.item("elven_longbow")
        define.item("elven_tinechel")
        define.item("ermaedril_tinechel")
        define.item("eye_of_heraphis")
        define.item("fire_dagger")
        define.item("fire_waraxe")
        define.item("florentine_dagger")
        define.item("giant_sword_of_doom")
        define.item("Gladius")
        define.item("halberd")
        define.item("hammerfist_axe")
        define.item("heavy_crossbow")
        define.item("improved_armored_bow")
        define.item("improved_composite_bow")
        define.item("improved_dirk")
        define.item("improved_double_axe")
        define.item("improved_dwarven_axe")
        define.item("improved_elven_blade")
        define.item("improved_elven_longbow")
        define.item("improved_elven_tinechel")
        define.item("improved_heavy_crossbow")
        define.item("improved_kryss")
        define.item("improved_longaxe")
        define.item("improved_longbow")
        define.item("improved_long_knife")
        define.item("improved_morningstar")
        define.item("improved_parrying_dagger")
        define.item("improved_shortbow")
        define.item("improved_trigadi_master_blade")
        define.item("improved_waraxe")
        define.item("improved_war_hammer")
        define.item("improved_war_mace")
        define.item("invari_parrying_blade")
        define.item("invari_seeker")
        define.item("ironclad_war_hammer")
        define.item("javelin")
        define.item("kryss")
        define.item("lightbringer")
        define.item("lightning_dagger")
        define.item("lightning_sword")
        define.item("longaxe")
        define.item("longbill")
        define.item("longbow")
        define.item("longmesser")
        define.item("longsword")
        define.item("long_knife")
        define.item("magical_firebow")
        define.item("magical_fire_longsword")
        define.item("magical_short_sword")
        define.item("magical_twohanded_sword")
        define.item("magical_waraxe")
        define.item("magical_war_mace")
        define.item("morningstar")
        define.item("optimized_longsword")
        define.item("orilian_sniper_bow")
        define.item("parrying_dagger")
        define.item("rapier")
        define.item("sabre")
        define.item("sadakari_sword")
        define.item("sakiras_valor")
        define.item("scimitar")
        define.item("shortbow")
        define.item("short_sword")
        define.item("short_sword_optimized")
        define.item("slingshot")
        define.item("spiked_club")
        define.item("staff_bone")
        define.item("staff_crooked")
        define.item("staff_ermaedril_battle")
        define.item("staff_journeyman")
        define.item("staff_quarter")
        define.item("staff_short")
        define.item("staff_wizard")
        define.item("thiefs_knife")
        define.item("throdins_might")
        define.item("throwing_star")
        define.item("thunder_mace")
        define.item("maruvian_hussar")
        define.item("maruvian_paladin_mace")
        define.item("trigadi_longbow")
        define.item("trigadi_master_blade")
        define.item("trigadi_signweaver")
        define.item("twohanded_sword")
        define.item("vormaedril_lytathrassel")
        define.item("vormaegal_raider_bow")
        define.item("vorrigans_gray_dagger")
        define.item("waraxe")
        define.item("warhammer")
        define.item("war_mace")
        define.item("will_of_calypso")
        define.item("yellowball_wand")

        define.item("catfish")
        define.item("cod")
        define.item("flounder")
        define.item("herring")
        define.item("pike")
        define.item("roach")
        define.item("salmon")
        define.item("sturgeon")
        define.item("tilapia")
        define.item("trout")
        define.item("tuna")
        define.item("claim_flag")
        define.item("apple")
        define.item("beef_dish")
        define.item("blueberry")
        define.item("blueberry_pie")
        define.item("blue_wine")
        define.item("bread")
        define.item("cabbage")
        define.item("carrot")

        define.item("carrot_cabbage_soup")
        define.item("carrot_cabbage_tomato_onion_salad")
        define.item("catfish_dish")
        define.item("cherry")
        define.item("cherry_pie")
        define.item("cod_dish")
        define.item("dark_wine")
        define.item("birthday_cake")
        define.item("elven_haliasel")
        define.item("flounder_dish")
        define.item("grape")
        define.item("grape_melon_lorma_apple_strawberry_fruit_salad")
        define.item("herring_dish")
        define.item("high_level_nabool_lorma_melon_fruit_salad")
        define.item("kassarean_valor")
        define.item("kernabu")
        define.item("lemon")
        define.item("limon_blueberry_cherry_apple_fruit_salad")
        define.item("lorma")
        define.item("mushroom_soup")
        define.item("mutton_dish")
        define.item("nabool")
        define.item("onion")
        define.item("onion_soup")
        define.item("pepper_vodka")
        define.item("pike_dish")
        define.item("pork_dish")
        define.item("raw_beef")
        define.item("raw_mutton")
        define.item("raw_pork")
        define.item("red_wine")
        define.item("roach_dish")
        define.item("rye_bread")
        define.item("rye_cookies")
        define.item("rye_vodka")
        define.item("salmon_dish")
        define.item("spicy_kernabu_soup")
        define.item("strawberry")
        define.item("strawberry_pie")
        define.item("sturgeon_dish")
        define.item("tilapia_dish")
        define.item("tomato")
        define.item("tomato_soup")
        define.item("maruvian_firewater")
        define.item("trout_dish")
        define.item("tuna_dish")
        define.item("vodka")
        define.item("watermelon")
        define.item("wheat_vodka")
        define.item("wine")
        define.item("golden_pot")
        define.item("alchemical_alembic_active_s")
        define.item("alchemical_alembic_active_w")
        define.item("alchemical_alembic_s")
        define.item("alchemical_alembic_w")
        define.item("alchemical_apparatus_s")
        define.item("alchemical_apparatus_w")
        define.item("alchemical_decomposer")
        define.item("alchemical_decomposer_active")
        define.item("alchemical_furnace")
        define.item("alchemical_furnace_active")
        define.item("alchemical_transmuter")
        define.item("alchemical_transmuter_active")
        define.item("alchemist_bench_s")
        define.item("alchemist_bench_w")
        define.item("brewing_stand")
        define.item("brewing_stand_active")
        define.item("calypso_altar")
        define.item("calypso_altar_full")
        define.item("heraphis_altar")
        define.item("heraphis_altar_full")
        define.item("lelei_altar")
        define.item("priroda_altar")
        define.item("priroda_altar_full")
        define.item("sakira_altar")
        define.item("sakira_altar_full")
        define.item("throdin_altar")
        define.item("anvil")
        define.item("anvil_active")
        define.item("new_anvil")
        define.item("new_anvil_hot_01")
        define.item("new_anvil_hot_02")
        define.item("new_anvil_hot_03")
        define.item("archery_target_s")
        define.item("archery_target_w")
        define.item("barrel")
        define.item("barrels_stacked_five")
        define.item("barrels_stacked_four_top_lying")
        define.item("barrels_stacked_three")
        define.item("barrel_stacked_two_top_lying")
        define.item("empty_barrel")
        define.item("lying_barrel")
        define.item("lying_barrels_stacked_five")
        define.item("lying_barrels_stacked_three")
        define.item("Water Barrell")
        define.item("water_barrel_01")
        define.item("wine_barrel_s")
        define.item("wine_barrel_w")
        define.item("bed_s")
        define.item("bed_single_w")
        define.item("double_bed_s")
        define.item("double_bed_w")
        define.item("fur_bed_s")
        define.item("fur_bed_w")
        define.item("loft_bed_s")
        define.item("loft_bed_w")
        define.item("bookshelf_01_s")
        define.item("bookshelf_01_w")
        define.item("bookshelf_02_s")
        define.item("bookshelf_02_w")
        define.item("bookshelf_03_s")
        define.item("bookshelf_03_w")
        define.item("bookshelf_04_s")
        define.item("bookshelf_04_w")
        define.item("bookshelf_05_s")
        define.item("bookshelf_05_w")
        define.item("green_carpet")
        define.item("red_carpet")
        define.item("chair_e")
        define.item("chair_n")
        define.item("chair_s")
        define.item("chair_w")
        define.item("office_chair_e")
        define.item("office_chair_n")
        define.item("office_chair_s")
        define.item("office_chair_w")
        define.item("stool")
        define.item("wooden_chair_e")
        define.item("wooden_chair_n")
        define.item("wooden_chair_s")
        define.item("wooden_chair_w")
        define.item("chest_s")
        define.item("chest_w")
        define.item("depot")
        define.item("large_wooden_chest_s")
        define.item("large_wooden_chest_w")
        define.item("red_chest_s")
        define.item("red_chest_w")
        define.item("trunk_s")
        define.item("trunk_w")
        define.item("bed_table_s")
        define.item("bed_table_w")
        define.item("closet_s")
        define.item("closet_w")
        define.item("blue_drapes_single_s")
        define.item("blue_drapes_single_w")
        define.item("red_drapes_double_s")
        define.item("red_drapes_double_w")
        define.item("red_drapes_red_single_w")
        define.item("red_drapes_single_s")
        define.item("fireplace_01")
        define.item("fireplace_01_active")
        define.item("fireplace_02")
        define.item("fireplace_02_active")
        define.item("furnace_active_s")
        define.item("furnace_active_w")
        define.item("furnace_s")
        define.item("furnace_w")
        define.item("gem_cutter_s")
        define.item("gem_cutter_w")
        define.item("harp_n")
        define.item("harp_w")
        define.item("leather_frame")
        define.item("loom")
        define.item("oil_grinder")
        define.item("oil_press")
        define.item("oven_active_s")
        define.item("oven_active_w")
        define.item("oven_s")
        define.item("oven_w")
        define.item("dragon_painting")
        define.item("railing_01_e")
        define.item("railing_01_n")
        define.item("railing_01_s")
        define.item("railing_01_w")
        define.item("railing_02_e")
        define.item("railing_02_n")
        define.item("railing_02_s")
        define.item("railing_02_w")
        define.item("railing_corner_ne")
        define.item("railing_corner_nw")
        define.item("railing_corner_se")
        define.item("railing_corner_sw")
        define.item("spinning_wheel")
        define.item("stone_grinder")
        define.item("bar_counter_long_s")
        define.item("bar_counter_long_w")
        define.item("bar_counter_s")
        define.item("bar_counter_w")
        define.item("brown_round_table")
        define.item("dark_round_table")
        define.item("gold_round_table")
        define.item("gray_round_table")
        define.item("oak_round_table")
        define.item("picnic_table_s")
        define.item("picnic_table_w")
        define.item("white_round_table")
        define.item("yellow_round_table")
        define.item("mounted_cow_trophy")


        define.item("mounted_creeptread_trophy")
        define.item("mounted_deer_trophy")
        define.item("mounted_dragon_trophy")
        define.item("amehyst")
        define.item("barrid")
        define.item("cut_amethyst")
        define.item("cut_barrid")
        define.item("cut_diamond")
        define.item("cut_dragonid")
        define.item("cut_emerald")
        define.item("cut_nalcarid")
        define.item("cut_ruby")
        define.item("cut_sapphire")
        define.item("cut_solite")
        define.item("diamond")
        define.item("dragonid")
        define.item("emerald")
        define.item("gem_dust")
        define.item("nalcarid")
        define.item("ruby")
        define.item("sapphire")
        define.item("solite")
        define.item("headstone_01")
        define.item("headstone_02")
        define.item("headstone_03")
        define.item("headstone_04")
        define.item("aspenmate_mushroom")
        define.item("azure_thistle")
        define.item("big_white")
        define.item("black_lily")
        define.item("blassar_leaf")
        define.item("cumbris")
        define.item("dandelion")
        define.item("drowning_clover")
        define.item("dunefang")
        define.item("erdorium_blossom")
        define.item("fox_flower")
        define.item("gnomes_mushroom")
        define.item("lions_yawn")
        define.item("littletoe")
        define.item("maple_root")
        define.item("pepperfrost")
        define.item("pig_parsley")
        define.item("pixies_blush")
        define.item("princes_bliss")
        define.item("queens_goblet")
        define.item("red_fool")
        define.item("rugaritz")
        define.item("stonecrow")
        define.item("threefoot")
        define.item("toadpetal")
        define.item("underbirch")
        define.item("verbena")
        define.item("virgins_flower")
        define.item("white_maiden_mushroom")
        define.item("willow_tears")
        define.item("wolfspoison")
        define.item("wormwool")
        define.item("copper_ingot")
        define.item("gold_ingot")
        define.item("iron_ingot")
        define.item("malphite_ingot")
        define.item("silver_ingot")
        define.item("teranium_ingot")
        define.item("bone")
        define.item("bottle")
        define.item("bowl")
        define.item("branch")
        define.item("building_site")
        define.item("candelabra")
        define.item("cut_logs")
        define.item("dough")
        define.item("feather")
        define.item("fish_guts")
        define.item("flour")
        define.item("fur")
        define.item("glass_panels")
        define.item("grain")
        define.item("herbivore_guts")
        define.item("honey")
        define.item("honeycomb")
        define.item("ink")
        define.item("insect_wing")
        define.item("leather")
        define.item("lit_candelabra")
        define.item("lock")
        define.item("locked_slot")
        define.item("logs")
        define.item("plate")
        define.item("potion")
        define.item("predator_guts")
        define.item("raw_leather")
        define.item("rye")
        define.item("rye_dough")
        define.item("rye_flour")
        define.item("rye_grain")
        define.item("sand")
        define.item("stones")
        define.item("straw")
        define.item("sugar")
        define.item("sunflower_oil")
        define.item("sunflower_paste")
        define.item("support_stakes")
        define.item("thread")
        define.item("treasure_map")
        define.item("undead_guts")
        define.item("vodka_bottle")
        define.item("water_bottle")
        define.item("wax")
        define.item("well")
        define.item("wheat")
        define.item("wine_bottle")
        define.item("wooden_stakes")
        define.item("wool")
        define.item("yarn")
        define.item("yeast")
        define.item("copper_dinari")
        define.item("copper_grivon")
        define.item("gold_dinari")
        define.item("gold_grivon")
        define.item("silver_dinari")
        define.item("silver_grivon")
        define.item("bare_bush_01")
        define.item("bush_01")
        define.item("bush_02")
        define.item("bush_03")
        define.item("bush_04")
        define.item("caeril_bush_02")
        define.item("caeril_bush_03")
        define.item("darkon_bush_01")
        define.item("darkon_bush_02")
        define.item("darkon_bush_03")
        define.item("dead_bush_01")
        define.item("dead_moor_bush_01")
        define.item("desert_bush_01")
        define.item("hemara_bush_01")
        define.item("hemara_bush_02")
        define.item("hemara_bush_03")
        define.item("blueberry_bush_01")
        define.item("blueberry_bush_01_full")
        define.item("kernabu_bush_01")
        define.item("kernabu_bush_01_full")
        define.item("flowers_01")
        define.item("flowers_02")
        define.item("flowers_03")
        define.item("flowers_04")
        define.item("flowers_05")
        define.item("flowers_06")
        define.item("flowers_07")
        define.item("grass_01")
        define.item("grass_02")
        define.item("grass_03")
        define.item("grass_04")
        define.item("grass_05")
        define.item("grass_06")
        define.item("grass_07")
        define.item("grass_08")
        define.item("grass_09")
        define.item("grass_10")
        define.item("grass_11")
        define.item("grass_12")
        define.item("grass_13")
        define.item("grass_14")
        define.item("mushrooms_01")
        define.item("mushrooms_02")
        define.item("mushrooms_03")
        define.item("mushrooms_04")
        define.item("mushrooms_05")
        define.item("mushroom_01")
        define.item("mushroom_02")
        define.item("mushroom_03")
        define.item("mushroom_circle_01")
        define.item("mushroom_circle_02")
        define.item("mushroom_circle_03")
        define.item("mushroom_circle_04")
        define.item("desert_plant_01")
        define.item("desert_plant_02")
        define.item("desert_plant_03")
        define.item("desert_plant_04")
        define.item("desert_plant_05")
        define.item("desert_plant_06")
        define.item("caeril_fern_01")
        define.item("caeril_fern_02")
        define.item("caeril_fern_03")
        define.item("caeril_fern_04")
        define.item("caeril_fern_05")
        define.item("caeril_fern_06")
        define.item("darkon_fern_01")
        define.item("darkon_fern_02")
        define.item("darkon_fern_03")
        define.item("darkon_fern_04")
        define.item("darkon_fern_05")
        define.item("darkon_fern_06")
        define.item("fern_01")
        define.item("fern_02")
        define.item("fern_03")
        define.item("fern_04")
        define.item("fern_05")

        define.item("fern_06")
        define.item("fern_07")
        define.item("fern_08")
        define.item("fern_09")
        define.item("fern_10")
        define.item("fern_11")
        define.item("fern_12")
        define.item("fern_13")
        define.item("fern_14")
        define.item("marsh_fern_01")
        define.item("swamp_fern_01")
        define.item("swamp_fern_02")
        define.item("forest_plants_01")
        define.item("forest_plants_02")
        define.item("lilies_01")
        define.item("lilies_02")
        define.item("lilies_03")
        define.item("lilies_04")
        define.item("water_plants_01")
        define.item("water_plants_02")
        define.item("water_plants_03")
        define.item("water_plants_04")
        define.item("water_plants_05")
        define.item("water_plants_06")
        define.item("reeds_01")
        define.item("reeds_02")
        define.item("reeds_03")
        define.item("desert_rock_01")
        define.item("forest_rock_01")
        define.item("rock_01")
        define.item("rock_02")
        define.item("rock_03")
        define.item("rock_04")
        define.item("rock_05")
        define.item("rock_06")
        define.item("rock_07")
        define.item("rock_08")
        define.item("rock_09")
        define.item("rock_10")
        define.item("rock_11")
        define.item("rock_12")
        define.item("rock_13")
        define.item("rock_14")
        define.item("rock_15")
        define.item("rock_16")
        define.item("rock_17")
        define.item("rock_18")
        define.item("rock_19")
        define.item("rock_20")
        define.item("rock_21")
        define.item("rock_22")
        define.item("rock_23")
        define.item("rock_24")
        define.item("rock_25")
        define.item("rock_pile_01")
        define.item("rock_pile_02")
        define.item("rock_pile_03")
        define.item("rock_pile_04")
        define.item("rock_pile_05")
        define.item("rock_pile_06")
        define.item("rock_pile_07")
        define.item("rock_pile_08")
        define.item("rock_pile_09")
        define.item("rock_pile_10")
        define.item("tiny_rock_01")
        define.item("tiny_rock_02")
        define.item("tiny_rock_03")
        define.item("tiny_rock_04")
        define.item("sunflowers_01")
        define.item("albizia_tree_01")
        define.item("apple_tree_01")
        define.item("apple_tree_02")
        define.item("apple_tree_03")
        define.item("apple_tree_cut_s")
        define.item("apple_tree_cut_w")
        define.item("arbutus_tree_01")
        define.item("arbutus_tree_02")
        define.item("arch_oak_tree_01")
        define.item("young_arch_oak_tree_01")
        define.item("aspen_tree_01")
        define.item("aspen_tree_02")
        define.item("aspen_tree_cut_s")
        define.item("aspen_tree_cut_w")
        define.item("young_aspen_tree")
        define.item("young_aspen_tree_02")
        define.item("young_aspen_tree_cut_s")
        define.item("young_aspen_tree_cut_w")
        define.item("bare_tree_01")
        define.item("bare_tree_02")
        define.item("birch_tree_01")
        define.item("birch_tree_cut_s")
        define.item("birch_tree_cut_w")
        define.item("darkon_birch_tree_01")
        define.item("northern_birch_tree_01")
        define.item("northern_birch_tree_02")
        define.item("southern_birch_tree_01")
        define.item("southern_birch_tree_02")
        define.item("southern_birch_tree_03")
        define.item("blue_spruce_tree_01")
        define.item("blue_spruce_tree_02")
        define.item("blue_spruce_tree_03")
        define.item("blue_spruce_tree_cut_s")
        define.item("blue_spruce_tree_cut_w")
        define.item("boabab_tree_01")
        define.item("brown_ortis_tree_01")
        define.item("brown_ortis_tree_02")
        define.item("butternut_tree_01")
        define.item("butternut_tree_02")
        define.item("cherry_tree_01")
        define.item("cherry_tree_01_full")
        define.item("cherry_tree_cut_s")
        define.item("cherry_tree_cut_w")
        define.item("crooked_dwarftop_01")
        define.item("crooked_dwarftop_02")
        define.item("crooked_dwarftop_03")
        define.item("crooked_dwarftop_04")
        define.item("dead_tree_01")
        define.item("dead_tree_02")
        define.item("desert_tree_01")
        define.item("desert_tree_cut_s")
        define.item("desert_tree_cut_w")
        define.item("elven_oak_tree_01")
        define.item("elven_oak_tree_02")
        define.item("fir_tree_01")
        define.item("fir_tree_02")
        define.item("fir_tree_cut_s")
        define.item("fir_tree_cut_w")
        define.item("green_aspen_tree_01")
        define.item("green_aspen_tree_02")
        define.item("green_aspen_tree_03")
        define.item("green_aspen_tree_04")
        define.item("green_aspen_tree_05")
        define.item("hemara_oak_tree_01")
        define.item("hemara_oak_tree_02")
        define.item("hemara_oak_tree_03")
        define.item("jungle_tree_01")
        define.item("jungle_tree_02")
        define.item("jungle_tree_03")
        define.item("jungle_tree_04")
        define.item("jungle_tree_05")
        define.item("jungle_tree_06")
        define.item("jungle_tree_07")
        define.item("jungle_tree_08")
        define.item("jungle_tree_09")
        define.item("jungle_tree_10")
        define.item("jungle_tree_11")
        define.item("jungle_tree_12")
        define.item("jungle_tree_13")
        define.item("jungle_tree_14")
        define.item("jungle_tree_15")
        define.item("lemon_tree_01")
        define.item("lemon_tree_01_full")
        define.item("lemon_tree_cut_s")
        define.item("lemon_tree_cut_w")
        define.item("maple_tree_01")
        define.item("maple_tree_cut_s")
        define.item("maple_tree_cut_w")
        define.item("caeril_nabool_tree_01")
        define.item("caeril_oak_tree_01")
        define.item("crooked_oak_tree_01")
        define.item("darkon_oak_tree_01")
        define.item("darkon_oak_tree_02")
        define.item("grandfather_oak_tree_01")
        define.item("oak_tree_01")
        define.item("tree_oak_cut_s")
        define.item("tree_oak_cut_w")
        define.item("young_oak_tree_01")
        define.item("young_oak_tree_cut_s")
        define.item("young_oak_tree_cut_w")
        define.item("old_oak_tree_01")
        define.item("old_oak_tree_02")
        define.item("old_oak_tree_03")
        define.item("old_oak_tree_04")
        define.item("palm_tree_01")
        define.item("palm_tree_02")
        define.item("palm_tree_03")
        define.item("palm_tree_04")
        define.item("palm_tree_cut_s")
        define.item("palm_tree_cut_w")
        define.item("tropical_palm_tree_01")
        define.item("tropical_palm_tree_02")
        define.item("pine_tree_01")
        define.item("pine_tree_02")
        define.item("pine_tree_03")
        define.item("pine_tree_04")
        define.item("pine_tree_cut_s")
        define.item("pine_tree_cut_w")
        define.item("darkon_popla_tree_01")
        define.item("green_popla_tree_01")
        define.item("redwood_tree_01")
        define.item("redwood_tree_02")
        define.item("redwood_tree_03")
        define.item("redwood_tree_04")
        define.item("redwood_tree_05")
        define.item("redwood_tree_06")
        define.item("skull_oak_tree_01")


        define.item("tropical_tree_01")
        define.item("whitebirch_tree_01")
        define.item("whitebirch_tree_02")
        define.item("whitebirch_tree_03")
        define.item("whitebirch_tree_04")
        define.item("marsh_weeds_01")
        define.item("moor_weeds_01")
        define.item("moor_weeds_02")
        define.item("moor_weeds_03")
        define.item("moor_weeds_04")
        define.item("moor_weeds_05")
        define.item("swamp_weeds_02")
        define.item("weeds_03")
        define.item("weeds_04")
        define.item("coal")
        define.item("copper_ore")
        define.item("gold_ore")
        define.item("iron_ore")
        define.item("malphite_ore")
        define.item("silver_ore")
        define.item("teranium_ore")
        define.item("copper_ring")
        define.item("gold_ring")
        define.item("malphite_ring")
        define.item("ring_overlay")
        define.item("silver_ring")
        define.item("teranium_ring")
        define.item("recipe_01")
        define.item("recipe_02")
        define.item("recipe_03")
        define.item("scroll")
        define.item("cabbage_seeds")
        define.item("carrot_seeds")
        define.item("grape_seeds")
        define.item("lorma_seeds")
        define.item("onion_seeds")
        define.item("sunflower_seeds")
        define.item("tomato_seeds")
        define.item("watermelon_seeds")
        define.item("roadsign_e")
        define.item("roadsign_n")
        define.item("roadsign_s")
        define.item("roadsign_w")
        define.item("sign_pole_e")
        define.item("sign_pole_n")
        define.item("wooden_sign_pole_e")
        define.item("wooden_sign_pole_n")
        define.item("cave_stairs_down_s")
        define.item("cave_stairs_down_w")
        define.item("cave_stairs_s")
        define.item("cave_stairs_w")
        define.item("hole_ladder_w")
        define.item("ladder_s")
        define.item("ladder_w")
        define.item("stairs_down_s")
        define.item("stairs_down_w")
        define.item("stairs_s")
        define.item("stairs_w")
        define.item("bishop_fountain")
        define.item("bishop_fountain_active")
        define.item("bladewing_fountain")
        define.item("bladewing_fountain_active")
        define.item("blood_fountain")
        define.item("bronze_sakira_statue_e")
        define.item("bronze_sakira_statue_s")
        define.item("bronze_sakira_statue_w")
        define.item("gold_lelei_statue_e")
        define.item("gold_lelei_statue_s")
        define.item("gold_lelei_statue_w")
        define.item("gold_throdin_statue_e")
        define.item("gold_throdin_statue_s")
        define.item("gold_throdin_statue_w")
        define.item("knight_statue_e")
        define.item("knight_statue_n")
        define.item("knight_statue_s")
        define.item("knight_statue_w")
        define.item("lelei_statue_n")
        define.item("lelei_statue_s")
        define.item("lelei_statue_w")
        define.item("obsidian_gargoyle_e")
        define.item("obsidian_gargoyle_s")
        define.item("obsidian_gargoyle_w")
        define.item("priroda_statue_e")
        define.item("priroda_statue_n")
        define.item("priroda_statue_s")
        define.item("priroda_statue_w")
        define.item("sakira_fountain")
        define.item("marble_column")
        define.item("brick_corner_ne")
        define.item("brick_corner_nw")
        define.item("brick_corner_se")
        define.item("brick_corner_sw")
        define.item("brick_door_e")
        define.item("brick_door_n")
        define.item("brick_door_open_e")
        define.item("brick_door_open_n")
        define.item("brick_door_open_s")
        define.item("brick_door_open_w")
        define.item("brick_door_s")
        define.item("brick_door_w")
        define.item("brick_triangle_e_n")
        define.item("brick_triangle_e_s")
        define.item("brick_triangle_n_e")
        define.item("brick_triangle_n_w")
        define.item("brick_triangle_s_e")
        define.item("brick_triangle_s_w")
        define.item("brick_triangle_w_n")
        define.item("brick_triangle_w_s")
        define.item("brick_wall_e")
        define.item("brick_wall_n")
        define.item("brick_wall_s")
        define.item("brick_wall_w")
        define.item("brick_window_e")
        define.item("brick_window_n")
        define.item("brick_window_s")
        define.item("brick_window_w")
        define.item("cave_wall_01")
        define.item("cave_wall_01_mini")
        define.item("mud_wall_01")
        define.item("mud_wall_01_mini")
        define.item("raw_stone_door_e")
        define.item("raw_stone_door_n")
        define.item("raw_stone_door_open_e")
        define.item("raw_stone_door_open_n")
        define.item("raw_stone_door_open_s")
        define.item("raw_stone_door_open_w")
        define.item("raw_stone_door_s")
        define.item("raw_stone_door_w")
        define.item("raw_stone_triangle_e_n")
        define.item("raw_stone_triangle_e_s")
        define.item("raw_stone_triangle_n_e")
        define.item("raw_stone_triangle_n_w")
        define.item("raw_stone_triangle_s_e")
        define.item("raw_stone_triangle_s_w")
        define.item("raw_stone_triangle_w_n")
        define.item("raw_stone_triangle_w_s")
        define.item("raw_stone_wall_beam_l_e")
        define.item("raw_stone_wall_beam_l_long_s")
        define.item("raw_stone_wall_beam_l_long_w")
        define.item("raw_stone_wall_beam_l_n")
        define.item("raw_stone_wall_beam_l_s")
        define.item("raw_stone_wall_beam_l_w")
        define.item("raw_stone_wall_beam_s")
        define.item("raw_stone_wall_beam_w")
        define.item("raw_stone_wall_e")
        define.item("raw_stone_wall_l_sign_s")
        define.item("raw_stone_wall_l_sign_w")
        define.item("raw_stone_wall_n")
        define.item("raw_stone_wall_s")
        define.item("raw_stone_wall_trim_s")
        define.item("raw_stone_wall_trim_w")
        define.item("raw_stone_wall_w")
        define.item("raw_stone_window_e")
        define.item("raw_stone_window_n")
        define.item("raw_stone_window_s")
        define.item("raw_stone_window_w")
        define.item("rock_face_01_s")
        define.item("rock_face_02_s")
        define.item("rock_face_03_s")
        define.item("rock_face_03_w")
        define.item("rock_face_04_s")
        define.item("rock_face_04_w")
        define.item("rock_face_corner")
        define.item("rock_face_corner_sw")
        define.item("rock_face_entry_s")
        define.item("rock_face_w")
        define.item("dark_roof_w")
        define.item("roof_s")
        define.item("roof_w")
        define.item("stucco_corner_ne")
        define.item("stucco_corner_nw")
        define.item("stucco_corner_se")
        define.item("stucco_corner_sw")
        define.item("stucco_door_e")
        define.item("stucco_door_n")
        define.item("stucco_door_open_e")
        define.item("stucco_door_open_n")
        define.item("stucco_door_open_s")
        define.item("stucco_door_open_w")
        define.item("stucco_door_s")
        define.item("stucco_door_w")
        define.item("stucco_pole")
        define.item("stucco_triangle_e_n")
        define.item("stucco_triangle_e_s")
        define.item("stucco_triangle_n_e")
        define.item("stucco_triangle_n_w")
        define.item("stucco_triangle_s_e")
        define.item("stucco_triangle_s_w")
        define.item("stucco_triangle_w_n")
        define.item("stucco_triangle_w_s")
        define.item("stucco_wall_backslash_s")
        define.item("stucco_wall_backslash_w")
        define.item("stucco_wall_beam_s")
        define.item("stucco_wall_beam_w")
        define.item("stucco_wall_e")
        define.item("stucco_wall_n")
        define.item("stucco_wall_s")
        define.item("stucco_wall_slash_s")
        define.item("stucco_wall_slash_w")
        define.item("stucco_wall_w")
        define.item("stucco_window_e")
        define.item("stucco_window_mw_s")
        define.item("stucco_window_mw_w")
        define.item("stucco_window_n")
        define.item("stucco_window_s")
        define.item("stucco_window_va_s")
        define.item("stucco_window_va_w")
        define.item("stucco_window_vv_s")
        define.item("stucco_window_vv_w")
        define.item("stucco_window_w")
        define.item("stucco_window_wm_s")
        define.item("stucco_window_wm_w")
        define.item("stucco_window_ww_w")
        define.item("stucco_window_w_s")
        define.item("uncut_stone_corner_ne")
        define.item("uncut_stone_corner_nw")
        define.item("uncut_stone_corner_se")
        define.item("uncut_stone_corner_sw")
        define.item("uncut_stone_wall_e")
        define.item("uncut_stone_wall_n")
        define.item("uncut_stone_wall_s")
        define.item("uncut_stone_wall_w")
        define.item("wood_corner_ne")
        define.item("wood_corner_nw")
        define.item("wood_corner_se")
        define.item("wood_corner_sw")
        define.item("wood_door_e")
        define.item("wood_door_n")
        define.item("wood_door_open_e")
        define.item("wood_door_open_n")
        define.item("wood_door_open_s")
        define.item("wood_door_open_w")
        define.item("wood_door_s")
        define.item("wood_door_w")
        define.item("wood_pillar_ne")
        define.item("wood_pillar_nw")
        define.item("wood_pillar_s")
        define.item("wood_pillar_se")
        define.item("wood_pillar_sw")
        define.item("wood_pillar_w")
        define.item("wood_triangle_e_n")
        define.item("wood_triangle_e_s")
        define.item("wood_triangle_n_e")
        define.item("wood_triangle_n_w")
        define.item("wood_triangle_s_e")
        define.item("wood_triangle_s_w")
        define.item("wood_triangle_w_n")
        define.item("wood_triangle_w_s")
        define.item("wood_trim_s")
        define.item("wood_trim_w")
        define.item("wood_wall_e")
        define.item("wood_wall_n")
        define.item("wood_wall_s")
        define.item("wood_wall_w")
        define.item("wood_window_e")
        define.item("wood_window_n")
        define.item("wood_window_s")
        define.item("wood_window_w")
        define.item("tent_e")
        define.item("tent_n")
        define.item("bag")
        define.item("brick_mold")
        define.item("bucket")
        define.item("bucket_overlay")
        define.item("builders_toolbox")
        define.item("carving_tools")
        define.item("cauldron")
        define.item("crucible")
        define.item("filter")
        define.item("fireworks")
        define.item("fishing_rod")
        define.item("flail")
        define.item("flint")
        define.item("flute")
        define.item("glassblowing_pipe")
        define.item("hammer")
        define.item("harp")
        define.item("hatchet")
        define.item("hoe")
        define.item("horn")
        define.item("key")
        define.item("knife")
        define.item("lit_torch")
        define.item("lockpicks")
        define.item("lute")
        define.item("lyre")
        define.item("mortar_and_pestle")
        define.item("needle")
        define.item("nephars_lucky_dice")
        define.item("object_kit")
        define.item("peel")
        define.item("pickaxe")
        define.item("plow")
        define.item("rake")
        define.item("razor")
        define.item("rolling_pin")
        define.item("rope")
        define.item("saw")
        define.item("scissors")
        define.item("scythe")
        define.item("shovel")
        define.item("sickle")
        define.item("smoking_pipe")
        define.item("tambourine")
        define.item("tongs")
        define.item("torch")
        define.item("turnscrew_set")
        define.item("water_bucket")
        define.item("wooden_spoon")
        define.item("woodplane")
        define.item("writing_feather")
        define.item("watermill")
    }
}